location ~ ^/plugin/([^/]+)/webdav/?$ {
    rewrite ^/plugin/([^/]+)/webdav/?$ /plugin/$1/webdav/index.html last;
}
location ~ ^/plugin/[^/]+/webdav/(.*)$ {
    proxy_pass http://127.0.0.1:18120/$1$is_args$args;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Xiaomi-Client-Verify $ssl_client_verify;
    proxy_set_header X-Xiaomi-Client-DN $ssl_client_s_dn;
    proxy_read_timeout 45s;
    client_max_body_size 16k;
    proxy_hide_header Server;
}
