const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../web');
// Xiaomi's MicroApp sandbox evaluates each script in a separate function scope.
const body = '// Generated by scripts/build_ui.cjs; edit app.js and access-ui.js.\n'
  + ['app.js', 'access-ui.js'].map(name => fs.readFileSync(path.join(root, name), 'utf8')).join('\n;\n');
fs.writeFileSync(path.join(root, 'app.bundle.js'), body);
console.log('Built shared-scope WebDAV UI entry');
